// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (user_id, title, description, public)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, description, public, created_at, updated_at
`

type CreateCollectionParams struct {
	UserID      uuid.UUID
	Title       string
	Description string
	Public      bool
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Public,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :one
DELETE FROM collections
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, public, created_at, updated_at
`

type DeleteCollectionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteCollection(ctx context.Context, arg DeleteCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, deleteCollection, arg.ID, arg.UserID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollection = `-- name: GetCollection :one
SELECT id, user_id, title, description, public, created_at, updated_at FROM collections
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetCollectionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetCollection(ctx context.Context, arg GetCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollection, arg.ID, arg.UserID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCollections = `-- name: ListCollections :many
SELECT id, user_id, title, description, public, created_at, updated_at FROM collections
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListCollections(ctx context.Context, userID uuid.UUID) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Public,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections
SET title = $3, description = $4, public = $5
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, public, created_at, updated_at
`

type UpdateCollectionParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Title       string
	Description string
	Public      bool
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Public,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
