// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (
    user_id, title, description, url, collection_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, title, description, url, collection_id, created_at, updated_at
`

type CreateResourceParams struct {
	UserID       uuid.UUID
	Title        string
	Description  string
	Url          string
	CollectionID uuid.NullUUID
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.CollectionID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.CollectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :one
DELETE FROM resources
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, url, collection_id, created_at, updated_at
`

type DeleteResourceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteResource(ctx context.Context, arg DeleteResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, deleteResource, arg.ID, arg.UserID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.CollectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResource = `-- name: GetResource :one
SELECT r.id, r.user_id, r.title, r.description, r.url, r.collection_id, r.created_at, r.updated_at, c.title AS collection_title
FROM resources r
    LEFT JOIN collections c ON r.collection_id = c.id
WHERE r.id = $1 AND r.user_id = $2
LIMIT 1
`

type GetResourceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetResourceRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Title           string
	Description     string
	Url             string
	CollectionID    uuid.NullUUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CollectionTitle pgtype.Text
}

func (q *Queries) GetResource(ctx context.Context, arg GetResourceParams) (GetResourceRow, error) {
	row := q.db.QueryRow(ctx, getResource, arg.ID, arg.UserID)
	var i GetResourceRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.CollectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CollectionTitle,
	)
	return i, err
}

const listResources = `-- name: ListResources :many
SELECT r.id, r.user_id, r.title, r.description, r.url, r.collection_id, r.created_at, r.updated_at, c.title AS collection_title
FROM resources r
    LEFT JOIN collections c ON r.collection_id = c.id
WHERE r.user_id = $1
ORDER BY r.created_at
`

type ListResourcesRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Title           string
	Description     string
	Url             string
	CollectionID    uuid.NullUUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CollectionTitle pgtype.Text
}

func (q *Queries) ListResources(ctx context.Context, userID uuid.UUID) ([]ListResourcesRow, error) {
	rows, err := q.db.Query(ctx, listResources, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourcesRow{}
	for rows.Next() {
		var i ListResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.CollectionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CollectionTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET
    title = $3,
    description = $4,
    url = $5,
    collection_id = $6
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, url, collection_id, created_at, updated_at
`

type UpdateResourceParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Title        string
	Description  string
	Url          string
	CollectionID uuid.NullUUID
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.CollectionID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.CollectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
