// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, hash, description, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, hash, description, expires_at, created_at, updated_at
`

type CreateSessionParams struct {
	UserID      uuid.UUID
	Hash        string
	Description *string
	ExpiresAt   time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.Hash,
		arg.Description,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.Description,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSessionByHash = `-- name: DeleteSessionByHash :exec
DELETE FROM sessions
WHERE hash = $1
`

func (q *Queries) DeleteSessionByHash(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByHash, hash)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUserID, userID)
	return err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT id, user_id, hash, description, expires_at, created_at, updated_at FROM sessions
WHERE hash = $1
LIMIT 1
`

func (q *Queries) GetSessionByHash(ctx context.Context, hash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, hash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.Description,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionExpiresAt = `-- name: UpdateSessionExpiresAt :one
UPDATE sessions
SET expires_at = $2
WHERE id = $1
RETURNING id, user_id, hash, description, expires_at, created_at, updated_at
`

type UpdateSessionExpiresAtParams struct {
	ID        uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) UpdateSessionExpiresAt(ctx context.Context, arg UpdateSessionExpiresAtParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionExpiresAt, arg.ID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.Description,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
