// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createResourceTag = `-- name: CreateResourceTag :exec
INSERT INTO resource_tags (resource_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateResourceTagParams struct {
	ResourceID uuid.UUID
	TagID      uuid.UUID
}

func (q *Queries) CreateResourceTag(ctx context.Context, arg CreateResourceTagParams) error {
	_, err := q.db.Exec(ctx, createResourceTag, arg.ResourceID, arg.TagID)
	return err
}

const deleteResourceTags = `-- name: DeleteResourceTags :exec
DELETE FROM resource_tags
WHERE resource_id = $1
`

func (q *Queries) DeleteResourceTags(ctx context.Context, resourceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteResourceTags, resourceID)
	return err
}

const deleteTag = `-- name: DeleteTag :one
DELETE FROM tags
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, created_at, updated_at
`

type DeleteTagParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, deleteTag, arg.ID, arg.UserID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT id, user_id, name, created_at, updated_at FROM tags
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetTagParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetTag(ctx context.Context, arg GetTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, arg.ID, arg.UserID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, user_id, name, created_at, updated_at FROM tags
WHERE user_id = $1 AND name = $2
LIMIT 1
`

type GetTagByNameParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagsForResource = `-- name: GetTagsForResource :many
SELECT t.name
FROM tags t
    JOIN resource_tags rt ON t.id = rt.tag_id
WHERE rt.resource_id = $1
`

func (q *Queries) GetTagsForResource(ctx context.Context, resourceID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getTagsForResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForResources = `-- name: GetTagsForResources :many
SELECT rt.resource_id, t.name
FROM resource_tags rt
    JOIN tags t ON t.id = rt.tag_id
WHERE rt.resource_id = ANY($1::uuid [])
`

type GetTagsForResourcesRow struct {
	ResourceID uuid.UUID
	Name       string
}

func (q *Queries) GetTagsForResources(ctx context.Context, dollar_1 []uuid.UUID) ([]GetTagsForResourcesRow, error) {
	rows, err := q.db.Query(ctx, getTagsForResources, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTagsForResourcesRow{}
	for rows.Next() {
		var i GetTagsForResourcesRow
		if err := rows.Scan(&i.ResourceID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.user_id, t.name, t.created_at, t.updated_at
FROM tags t
    LEFT JOIN resource_tags rt ON t.id = rt.tag_id
WHERE t.user_id = $1
GROUP BY t.id
ORDER BY COUNT(rt.resource_id) DESC, t.name
`

func (q *Queries) ListTags(ctx context.Context, userID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name = $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, created_at, updated_at
`

type UpdateTagParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Name   string
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (user_id, name)
VALUES ($1, $2)
ON CONFLICT (user_id, name) DO NOTHING
RETURNING id, user_id, name, created_at, updated_at
`

type UpsertTagParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
